#######################
### Global JS tasks ###
#######################

[tasks.install]
description = "Install all JS dependencies"
run = "pnpm install"

[tasks.check]
description = "Lint and format all JS packages"
run = "mise run //js/...:check"

[tasks."check:ci"]
description = "Check if all JS packages are linted and formatted properly"
run = "mise run //js/...:check:ci"

[tasks.typecheck]
description = "Typecheck all JS packages"
run = "mise run //js/...:typecheck"

[tasks.test]
description = "Test all JS packages"
run = "mise run //js/...:test"

[tasks.build]
description = "Build all JS packages"
run = "mise run //js/...:build"
