#######################
### Global JS tasks ###
#######################

[tasks.install]
description = "Install all JS dependencies"
run = "pnpm install"

[tasks.check]
description = "Lint and format all JS packages"
depends = ["//js/...:check"]

[tasks."check:ci"]
description = "Check if all JS packages are linted and formatted properly"
depends = ["//js/...:check:ci"]

[tasks.codegen]
description = "Run all code generation scripts in JS projects"
depends = ["//js/...:codegen"]

[tasks."codegen:check"]
description = "Check if the generated files of all JS packages are up to date"
depends = ["//js/...:codegen:check"]

[tasks.typecheck]
description = "Typecheck all JS packages"
depends = ["//js/...:typecheck"]

[tasks.test]
description = "Test all JS packages"
depends = ["//js/...:test"]

[tasks.build]
description = "Build all JS packages"
depends = ["//js/...:build"]
