import type { IconRegistry } from "@astryxdesign/core/Icon";
import {
  ArrowDownIcon,
  ArrowSquareOutIcon,
  ArrowsDownUpIcon,
  ArrowUpIcon,
  CalendarBlankIcon,
  CaretDoubleLeftIcon,
  CaretDoubleRightIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ChecksIcon,
  ClockIcon,
  ColumnsIcon,
  CopyIcon,
  DotsThreeIcon,
  EyeSlashIcon,
  FunnelIcon,
  InfoIcon,
  ListIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  StopIcon,
  WarningIcon,
  WrenchIcon,
  XCircleIcon,
  XIcon,
} from "@phosphor-icons/react";
// biome-ignore lint/correctness/noUnusedImports: The Astryx CLI needs this import present
import React from "react";

const iconProps = {
  size: "1em",
  "aria-hidden": true as const,
};

export const neutralIconRegistry: IconRegistry = {
  close: <XIcon {...iconProps} />,
  chevronDown: <CaretDownIcon {...iconProps} />,
  chevronLeft: <CaretLeftIcon {...iconProps} />,
  chevronRight: <CaretRightIcon {...iconProps} />,
  chevronsLeft: <CaretDoubleLeftIcon {...iconProps} />,
  chevronsRight: <CaretDoubleRightIcon {...iconProps} />,
  check: <CheckIcon {...iconProps} />,
  success: <CheckCircleIcon {...iconProps} />,
  error: <XCircleIcon {...iconProps} />,
  warning: <WarningIcon {...iconProps} />,
  info: <InfoIcon {...iconProps} />,
  calendar: <CalendarBlankIcon {...iconProps} />,
  clock: <ClockIcon {...iconProps} />,
  externalLink: <ArrowSquareOutIcon {...iconProps} />,
  menu: <ListIcon {...iconProps} />,
  moreHorizontal: <DotsThreeIcon {...iconProps} />,
  search: <MagnifyingGlassIcon {...iconProps} />,
  arrowUp: <ArrowUpIcon {...iconProps} />,
  arrowDown: <ArrowDownIcon {...iconProps} />,
  arrowsUpDown: <ArrowsDownUpIcon {...iconProps} />,
  funnel: <FunnelIcon {...iconProps} />,
  eyeSlash: <EyeSlashIcon {...iconProps} />,
  viewColumns: <ColumnsIcon {...iconProps} />,
  copy: <CopyIcon {...iconProps} />,
  checkDouble: <ChecksIcon {...iconProps} />,
  wrench: <WrenchIcon {...iconProps} />,
  stop: <StopIcon {...iconProps} />,
  microphone: <MicrophoneIcon {...iconProps} />,
};
