/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnonymousRouteImport } from './routes/_anonymous'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AnonymousLoginRouteImport } from './routes/_anonymous/login'
import { Route as AnonymousSignupRouteImport } from './routes/_anonymous/signup'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedOOrganizationIdRouteImport } from './routes/_authenticated/o/$organizationId'
import { Route as AuthenticatedOOrganizationIdIndexRouteImport } from './routes/_authenticated/o/$organizationId/index'
import { Route as AuthenticatedOOrganizationIdEnvironmentsIndexRouteImport } from './routes/_authenticated/o/$organizationId/environments/index'
import { Route as AuthenticatedOOrganizationIdEnvironmentsCreateRouteImport } from './routes/_authenticated/o/$organizationId/environments/create'
import { Route as AuthenticatedOOrganizationIdFlagsIndexRouteImport } from './routes/_authenticated/o/$organizationId/flags/index'
import { Route as AuthenticatedOOrganizationIdFlagsCreateRouteImport } from './routes/_authenticated/o/$organizationId/flags/create'
import { Route as AuthenticatedOOrganizationIdProjectsIndexRouteImport } from './routes/_authenticated/o/$organizationId/projects/index'
import { Route as AuthenticatedOOrganizationIdProjectsCreateRouteImport } from './routes/_authenticated/o/$organizationId/projects/create'
import { Route as AuthenticatedOOrganizationIdProjectProjectNameIndexRouteImport } from './routes/_authenticated/o/$organizationId/project/$projectName/index'
import { Route as AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRouteImport } from './routes/_authenticated/o/$organizationId/project/$projectName/environment/$environmentName'
import { Route as AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRouteImport } from './routes/_authenticated/o/$organizationId/project/$projectName/flag/$flagName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousRoute = AnonymousRouteImport.update({
  id: '/_anonymous',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousLoginRoute = AnonymousLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AnonymousRoute,
} as any)
const AnonymousSignupRoute = AnonymousSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AnonymousRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOOrganizationIdRoute =
  AuthenticatedOOrganizationIdRouteImport.update({
    id: '/o/$organizationId',
    path: '/o/$organizationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOOrganizationIdIndexRoute =
  AuthenticatedOOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOOrganizationIdRoute,
  } as any)
const AuthenticatedOOrganizationIdEnvironmentsIndexRoute =
  AuthenticatedOOrganizationIdEnvironmentsIndexRouteImport.update({
    id: '/environments/',
    path: '/environments/',
    getParentRoute: () => AuthenticatedOOrganizationIdRoute,
  } as any)
const AuthenticatedOOrganizationIdEnvironmentsCreateRoute =
  AuthenticatedOOrganizationIdEnvironmentsCreateRouteImport.update({
    id: '/environments/create',
    path: '/environments/create',
    getParentRoute: () => AuthenticatedOOrganizationIdRoute,
  } as any)
const AuthenticatedOOrganizationIdFlagsIndexRoute =
  AuthenticatedOOrganizationIdFlagsIndexRouteImport.update({
    id: '/flags/',
    path: '/flags/',
    getParentRoute: () => AuthenticatedOOrganizationIdRoute,
  } as any)
const AuthenticatedOOrganizationIdFlagsCreateRoute =
  AuthenticatedOOrganizationIdFlagsCreateRouteImport.update({
    id: '/flags/create',
    path: '/flags/create',
    getParentRoute: () => AuthenticatedOOrganizationIdRoute,
  } as any)
const AuthenticatedOOrganizationIdProjectsIndexRoute =
  AuthenticatedOOrganizationIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedOOrganizationIdRoute,
  } as any)
const AuthenticatedOOrganizationIdProjectsCreateRoute =
  AuthenticatedOOrganizationIdProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedOOrganizationIdRoute,
  } as any)
const AuthenticatedOOrganizationIdProjectProjectNameIndexRoute =
  AuthenticatedOOrganizationIdProjectProjectNameIndexRouteImport.update({
    id: '/project/$projectName/',
    path: '/project/$projectName/',
    getParentRoute: () => AuthenticatedOOrganizationIdRoute,
  } as any)
const AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRoute =
  AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRouteImport.update(
    {
      id: '/project/$projectName/environment/$environmentName',
      path: '/project/$projectName/environment/$environmentName',
      getParentRoute: () => AuthenticatedOOrganizationIdRoute,
    } as any,
  )
const AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRoute =
  AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRouteImport.update({
    id: '/project/$projectName/flag/$flagName',
    path: '/project/$projectName/flag/$flagName',
    getParentRoute: () => AuthenticatedOOrganizationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AnonymousLoginRoute
  '/signup': typeof AnonymousSignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/o/$organizationId': typeof AuthenticatedOOrganizationIdRouteWithChildren
  '/o/$organizationId/': typeof AuthenticatedOOrganizationIdIndexRoute
  '/o/$organizationId/environments/create': typeof AuthenticatedOOrganizationIdEnvironmentsCreateRoute
  '/o/$organizationId/flags/create': typeof AuthenticatedOOrganizationIdFlagsCreateRoute
  '/o/$organizationId/projects/create': typeof AuthenticatedOOrganizationIdProjectsCreateRoute
  '/o/$organizationId/environments/': typeof AuthenticatedOOrganizationIdEnvironmentsIndexRoute
  '/o/$organizationId/flags/': typeof AuthenticatedOOrganizationIdFlagsIndexRoute
  '/o/$organizationId/projects/': typeof AuthenticatedOOrganizationIdProjectsIndexRoute
  '/o/$organizationId/project/$projectName/': typeof AuthenticatedOOrganizationIdProjectProjectNameIndexRoute
  '/o/$organizationId/project/$projectName/environment/$environmentName': typeof AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRoute
  '/o/$organizationId/project/$projectName/flag/$flagName': typeof AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AnonymousLoginRoute
  '/signup': typeof AnonymousSignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/o/$organizationId': typeof AuthenticatedOOrganizationIdIndexRoute
  '/o/$organizationId/environments/create': typeof AuthenticatedOOrganizationIdEnvironmentsCreateRoute
  '/o/$organizationId/flags/create': typeof AuthenticatedOOrganizationIdFlagsCreateRoute
  '/o/$organizationId/projects/create': typeof AuthenticatedOOrganizationIdProjectsCreateRoute
  '/o/$organizationId/environments': typeof AuthenticatedOOrganizationIdEnvironmentsIndexRoute
  '/o/$organizationId/flags': typeof AuthenticatedOOrganizationIdFlagsIndexRoute
  '/o/$organizationId/projects': typeof AuthenticatedOOrganizationIdProjectsIndexRoute
  '/o/$organizationId/project/$projectName': typeof AuthenticatedOOrganizationIdProjectProjectNameIndexRoute
  '/o/$organizationId/project/$projectName/environment/$environmentName': typeof AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRoute
  '/o/$organizationId/project/$projectName/flag/$flagName': typeof AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_anonymous': typeof AnonymousRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_anonymous/login': typeof AnonymousLoginRoute
  '/_anonymous/signup': typeof AnonymousSignupRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/o/$organizationId': typeof AuthenticatedOOrganizationIdRouteWithChildren
  '/_authenticated/o/$organizationId/': typeof AuthenticatedOOrganizationIdIndexRoute
  '/_authenticated/o/$organizationId/environments/create': typeof AuthenticatedOOrganizationIdEnvironmentsCreateRoute
  '/_authenticated/o/$organizationId/flags/create': typeof AuthenticatedOOrganizationIdFlagsCreateRoute
  '/_authenticated/o/$organizationId/projects/create': typeof AuthenticatedOOrganizationIdProjectsCreateRoute
  '/_authenticated/o/$organizationId/environments/': typeof AuthenticatedOOrganizationIdEnvironmentsIndexRoute
  '/_authenticated/o/$organizationId/flags/': typeof AuthenticatedOOrganizationIdFlagsIndexRoute
  '/_authenticated/o/$organizationId/projects/': typeof AuthenticatedOOrganizationIdProjectsIndexRoute
  '/_authenticated/o/$organizationId/project/$projectName/': typeof AuthenticatedOOrganizationIdProjectProjectNameIndexRoute
  '/_authenticated/o/$organizationId/project/$projectName/environment/$environmentName': typeof AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRoute
  '/_authenticated/o/$organizationId/project/$projectName/flag/$flagName': typeof AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/o/$organizationId'
    | '/o/$organizationId/'
    | '/o/$organizationId/environments/create'
    | '/o/$organizationId/flags/create'
    | '/o/$organizationId/projects/create'
    | '/o/$organizationId/environments/'
    | '/o/$organizationId/flags/'
    | '/o/$organizationId/projects/'
    | '/o/$organizationId/project/$projectName/'
    | '/o/$organizationId/project/$projectName/environment/$environmentName'
    | '/o/$organizationId/project/$projectName/flag/$flagName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/o/$organizationId'
    | '/o/$organizationId/environments/create'
    | '/o/$organizationId/flags/create'
    | '/o/$organizationId/projects/create'
    | '/o/$organizationId/environments'
    | '/o/$organizationId/flags'
    | '/o/$organizationId/projects'
    | '/o/$organizationId/project/$projectName'
    | '/o/$organizationId/project/$projectName/environment/$environmentName'
    | '/o/$organizationId/project/$projectName/flag/$flagName'
  id:
    | '__root__'
    | '/'
    | '/_anonymous'
    | '/_authenticated'
    | '/_anonymous/login'
    | '/_anonymous/signup'
    | '/_authenticated/home'
    | '/_authenticated/o/$organizationId'
    | '/_authenticated/o/$organizationId/'
    | '/_authenticated/o/$organizationId/environments/create'
    | '/_authenticated/o/$organizationId/flags/create'
    | '/_authenticated/o/$organizationId/projects/create'
    | '/_authenticated/o/$organizationId/environments/'
    | '/_authenticated/o/$organizationId/flags/'
    | '/_authenticated/o/$organizationId/projects/'
    | '/_authenticated/o/$organizationId/project/$projectName/'
    | '/_authenticated/o/$organizationId/project/$projectName/environment/$environmentName'
    | '/_authenticated/o/$organizationId/project/$projectName/flag/$flagName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnonymousRoute: typeof AnonymousRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anonymous': {
      id: '/_anonymous'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AnonymousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anonymous/login': {
      id: '/_anonymous/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AnonymousLoginRouteImport
      parentRoute: typeof AnonymousRoute
    }
    '/_anonymous/signup': {
      id: '/_anonymous/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AnonymousSignupRouteImport
      parentRoute: typeof AnonymousRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/o/$organizationId': {
      id: '/_authenticated/o/$organizationId'
      path: '/o/$organizationId'
      fullPath: '/o/$organizationId'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/o/$organizationId/': {
      id: '/_authenticated/o/$organizationId/'
      path: '/'
      fullPath: '/o/$organizationId/'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdIndexRouteImport
      parentRoute: typeof AuthenticatedOOrganizationIdRoute
    }
    '/_authenticated/o/$organizationId/environments/': {
      id: '/_authenticated/o/$organizationId/environments/'
      path: '/environments'
      fullPath: '/o/$organizationId/environments/'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdEnvironmentsIndexRouteImport
      parentRoute: typeof AuthenticatedOOrganizationIdRoute
    }
    '/_authenticated/o/$organizationId/environments/create': {
      id: '/_authenticated/o/$organizationId/environments/create'
      path: '/environments/create'
      fullPath: '/o/$organizationId/environments/create'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdEnvironmentsCreateRouteImport
      parentRoute: typeof AuthenticatedOOrganizationIdRoute
    }
    '/_authenticated/o/$organizationId/flags/': {
      id: '/_authenticated/o/$organizationId/flags/'
      path: '/flags'
      fullPath: '/o/$organizationId/flags/'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdFlagsIndexRouteImport
      parentRoute: typeof AuthenticatedOOrganizationIdRoute
    }
    '/_authenticated/o/$organizationId/flags/create': {
      id: '/_authenticated/o/$organizationId/flags/create'
      path: '/flags/create'
      fullPath: '/o/$organizationId/flags/create'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdFlagsCreateRouteImport
      parentRoute: typeof AuthenticatedOOrganizationIdRoute
    }
    '/_authenticated/o/$organizationId/projects/': {
      id: '/_authenticated/o/$organizationId/projects/'
      path: '/projects'
      fullPath: '/o/$organizationId/projects/'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedOOrganizationIdRoute
    }
    '/_authenticated/o/$organizationId/projects/create': {
      id: '/_authenticated/o/$organizationId/projects/create'
      path: '/projects/create'
      fullPath: '/o/$organizationId/projects/create'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedOOrganizationIdRoute
    }
    '/_authenticated/o/$organizationId/project/$projectName/': {
      id: '/_authenticated/o/$organizationId/project/$projectName/'
      path: '/project/$projectName'
      fullPath: '/o/$organizationId/project/$projectName/'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdProjectProjectNameIndexRouteImport
      parentRoute: typeof AuthenticatedOOrganizationIdRoute
    }
    '/_authenticated/o/$organizationId/project/$projectName/environment/$environmentName': {
      id: '/_authenticated/o/$organizationId/project/$projectName/environment/$environmentName'
      path: '/project/$projectName/environment/$environmentName'
      fullPath: '/o/$organizationId/project/$projectName/environment/$environmentName'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRouteImport
      parentRoute: typeof AuthenticatedOOrganizationIdRoute
    }
    '/_authenticated/o/$organizationId/project/$projectName/flag/$flagName': {
      id: '/_authenticated/o/$organizationId/project/$projectName/flag/$flagName'
      path: '/project/$projectName/flag/$flagName'
      fullPath: '/o/$organizationId/project/$projectName/flag/$flagName'
      preLoaderRoute: typeof AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRouteImport
      parentRoute: typeof AuthenticatedOOrganizationIdRoute
    }
  }
}

interface AnonymousRouteChildren {
  AnonymousLoginRoute: typeof AnonymousLoginRoute
  AnonymousSignupRoute: typeof AnonymousSignupRoute
}

const AnonymousRouteChildren: AnonymousRouteChildren = {
  AnonymousLoginRoute: AnonymousLoginRoute,
  AnonymousSignupRoute: AnonymousSignupRoute,
}

const AnonymousRouteWithChildren = AnonymousRoute._addFileChildren(
  AnonymousRouteChildren,
)

interface AuthenticatedOOrganizationIdRouteChildren {
  AuthenticatedOOrganizationIdIndexRoute: typeof AuthenticatedOOrganizationIdIndexRoute
  AuthenticatedOOrganizationIdEnvironmentsCreateRoute: typeof AuthenticatedOOrganizationIdEnvironmentsCreateRoute
  AuthenticatedOOrganizationIdFlagsCreateRoute: typeof AuthenticatedOOrganizationIdFlagsCreateRoute
  AuthenticatedOOrganizationIdProjectsCreateRoute: typeof AuthenticatedOOrganizationIdProjectsCreateRoute
  AuthenticatedOOrganizationIdEnvironmentsIndexRoute: typeof AuthenticatedOOrganizationIdEnvironmentsIndexRoute
  AuthenticatedOOrganizationIdFlagsIndexRoute: typeof AuthenticatedOOrganizationIdFlagsIndexRoute
  AuthenticatedOOrganizationIdProjectsIndexRoute: typeof AuthenticatedOOrganizationIdProjectsIndexRoute
  AuthenticatedOOrganizationIdProjectProjectNameIndexRoute: typeof AuthenticatedOOrganizationIdProjectProjectNameIndexRoute
  AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRoute: typeof AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRoute
  AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRoute: typeof AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRoute
}

const AuthenticatedOOrganizationIdRouteChildren: AuthenticatedOOrganizationIdRouteChildren =
  {
    AuthenticatedOOrganizationIdIndexRoute:
      AuthenticatedOOrganizationIdIndexRoute,
    AuthenticatedOOrganizationIdEnvironmentsCreateRoute:
      AuthenticatedOOrganizationIdEnvironmentsCreateRoute,
    AuthenticatedOOrganizationIdFlagsCreateRoute:
      AuthenticatedOOrganizationIdFlagsCreateRoute,
    AuthenticatedOOrganizationIdProjectsCreateRoute:
      AuthenticatedOOrganizationIdProjectsCreateRoute,
    AuthenticatedOOrganizationIdEnvironmentsIndexRoute:
      AuthenticatedOOrganizationIdEnvironmentsIndexRoute,
    AuthenticatedOOrganizationIdFlagsIndexRoute:
      AuthenticatedOOrganizationIdFlagsIndexRoute,
    AuthenticatedOOrganizationIdProjectsIndexRoute:
      AuthenticatedOOrganizationIdProjectsIndexRoute,
    AuthenticatedOOrganizationIdProjectProjectNameIndexRoute:
      AuthenticatedOOrganizationIdProjectProjectNameIndexRoute,
    AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRoute:
      AuthenticatedOOrganizationIdProjectProjectNameEnvironmentEnvironmentNameRoute,
    AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRoute:
      AuthenticatedOOrganizationIdProjectProjectNameFlagFlagNameRoute,
  }

const AuthenticatedOOrganizationIdRouteWithChildren =
  AuthenticatedOOrganizationIdRoute._addFileChildren(
    AuthenticatedOOrganizationIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedOOrganizationIdRoute: typeof AuthenticatedOOrganizationIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedOOrganizationIdRoute:
    AuthenticatedOOrganizationIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnonymousRoute: AnonymousRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
