/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnonymousRouteImport } from './routes/_anonymous'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AnonymousLoginRouteImport } from './routes/_anonymous/login'
import { Route as AnonymousSignupRouteImport } from './routes/_anonymous/signup'
import { Route as AuthenticatedOrganizationRequiredRouteImport } from './routes/_authenticated/_organizationRequired'
import { Route as AuthenticatedOrganizationRequiredHomeRouteImport } from './routes/_authenticated/_organizationRequired/home'
import { Route as AuthenticatedOrganizationRequiredEnvironmentsIndexRouteImport } from './routes/_authenticated/_organizationRequired/environments/index'
import { Route as AuthenticatedOrganizationRequiredEnvironmentsCreateRouteImport } from './routes/_authenticated/_organizationRequired/environments/create'
import { Route as AuthenticatedOrganizationRequiredFlagsIndexRouteImport } from './routes/_authenticated/_organizationRequired/flags/index'
import { Route as AuthenticatedOrganizationRequiredFlagsCreateRouteImport } from './routes/_authenticated/_organizationRequired/flags/create'
import { Route as AuthenticatedOrganizationRequiredProjectsIndexRouteImport } from './routes/_authenticated/_organizationRequired/projects/index'
import { Route as AuthenticatedOrganizationRequiredProjectsCreateRouteImport } from './routes/_authenticated/_organizationRequired/projects/create'
import { Route as AuthenticatedOrganizationRequiredProjectProjectNameIndexRouteImport } from './routes/_authenticated/_organizationRequired/project/$projectName/index'
import { Route as AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRouteImport } from './routes/_authenticated/_organizationRequired/project/$projectName/environment/$environmentName'
import { Route as AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRouteImport } from './routes/_authenticated/_organizationRequired/project/$projectName/flag/$flagName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousRoute = AnonymousRouteImport.update({
  id: '/_anonymous',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousLoginRoute = AnonymousLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AnonymousRoute,
} as any)
const AnonymousSignupRoute = AnonymousSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AnonymousRoute,
} as any)
const AuthenticatedOrganizationRequiredRoute =
  AuthenticatedOrganizationRequiredRouteImport.update({
    id: '/_organizationRequired',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationRequiredHomeRoute =
  AuthenticatedOrganizationRequiredHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredEnvironmentsIndexRoute =
  AuthenticatedOrganizationRequiredEnvironmentsIndexRouteImport.update({
    id: '/environments/',
    path: '/environments/',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredEnvironmentsCreateRoute =
  AuthenticatedOrganizationRequiredEnvironmentsCreateRouteImport.update({
    id: '/environments/create',
    path: '/environments/create',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredFlagsIndexRoute =
  AuthenticatedOrganizationRequiredFlagsIndexRouteImport.update({
    id: '/flags/',
    path: '/flags/',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredFlagsCreateRoute =
  AuthenticatedOrganizationRequiredFlagsCreateRouteImport.update({
    id: '/flags/create',
    path: '/flags/create',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredProjectsIndexRoute =
  AuthenticatedOrganizationRequiredProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredProjectsCreateRoute =
  AuthenticatedOrganizationRequiredProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredProjectProjectNameIndexRoute =
  AuthenticatedOrganizationRequiredProjectProjectNameIndexRouteImport.update({
    id: '/project/$projectName/',
    path: '/project/$projectName/',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRoute =
  AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRouteImport.update(
    {
      id: '/project/$projectName/environment/$environmentName',
      path: '/project/$projectName/environment/$environmentName',
      getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
    } as any,
  )
const AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRoute =
  AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRouteImport.update(
    {
      id: '/project/$projectName/flag/$flagName',
      path: '/project/$projectName/flag/$flagName',
      getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AnonymousLoginRoute
  '/signup': typeof AnonymousSignupRoute
  '/home': typeof AuthenticatedOrganizationRequiredHomeRoute
  '/environments/create': typeof AuthenticatedOrganizationRequiredEnvironmentsCreateRoute
  '/flags/create': typeof AuthenticatedOrganizationRequiredFlagsCreateRoute
  '/projects/create': typeof AuthenticatedOrganizationRequiredProjectsCreateRoute
  '/environments/': typeof AuthenticatedOrganizationRequiredEnvironmentsIndexRoute
  '/flags/': typeof AuthenticatedOrganizationRequiredFlagsIndexRoute
  '/projects/': typeof AuthenticatedOrganizationRequiredProjectsIndexRoute
  '/project/$projectName/': typeof AuthenticatedOrganizationRequiredProjectProjectNameIndexRoute
  '/project/$projectName/environment/$environmentName': typeof AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRoute
  '/project/$projectName/flag/$flagName': typeof AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AnonymousLoginRoute
  '/signup': typeof AnonymousSignupRoute
  '/home': typeof AuthenticatedOrganizationRequiredHomeRoute
  '/environments/create': typeof AuthenticatedOrganizationRequiredEnvironmentsCreateRoute
  '/flags/create': typeof AuthenticatedOrganizationRequiredFlagsCreateRoute
  '/projects/create': typeof AuthenticatedOrganizationRequiredProjectsCreateRoute
  '/environments': typeof AuthenticatedOrganizationRequiredEnvironmentsIndexRoute
  '/flags': typeof AuthenticatedOrganizationRequiredFlagsIndexRoute
  '/projects': typeof AuthenticatedOrganizationRequiredProjectsIndexRoute
  '/project/$projectName': typeof AuthenticatedOrganizationRequiredProjectProjectNameIndexRoute
  '/project/$projectName/environment/$environmentName': typeof AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRoute
  '/project/$projectName/flag/$flagName': typeof AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_anonymous': typeof AnonymousRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_anonymous/login': typeof AnonymousLoginRoute
  '/_anonymous/signup': typeof AnonymousSignupRoute
  '/_authenticated/_organizationRequired': typeof AuthenticatedOrganizationRequiredRouteWithChildren
  '/_authenticated/_organizationRequired/home': typeof AuthenticatedOrganizationRequiredHomeRoute
  '/_authenticated/_organizationRequired/environments/create': typeof AuthenticatedOrganizationRequiredEnvironmentsCreateRoute
  '/_authenticated/_organizationRequired/flags/create': typeof AuthenticatedOrganizationRequiredFlagsCreateRoute
  '/_authenticated/_organizationRequired/projects/create': typeof AuthenticatedOrganizationRequiredProjectsCreateRoute
  '/_authenticated/_organizationRequired/environments/': typeof AuthenticatedOrganizationRequiredEnvironmentsIndexRoute
  '/_authenticated/_organizationRequired/flags/': typeof AuthenticatedOrganizationRequiredFlagsIndexRoute
  '/_authenticated/_organizationRequired/projects/': typeof AuthenticatedOrganizationRequiredProjectsIndexRoute
  '/_authenticated/_organizationRequired/project/$projectName/': typeof AuthenticatedOrganizationRequiredProjectProjectNameIndexRoute
  '/_authenticated/_organizationRequired/project/$projectName/environment/$environmentName': typeof AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRoute
  '/_authenticated/_organizationRequired/project/$projectName/flag/$flagName': typeof AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/environments/create'
    | '/flags/create'
    | '/projects/create'
    | '/environments/'
    | '/flags/'
    | '/projects/'
    | '/project/$projectName/'
    | '/project/$projectName/environment/$environmentName'
    | '/project/$projectName/flag/$flagName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/environments/create'
    | '/flags/create'
    | '/projects/create'
    | '/environments'
    | '/flags'
    | '/projects'
    | '/project/$projectName'
    | '/project/$projectName/environment/$environmentName'
    | '/project/$projectName/flag/$flagName'
  id:
    | '__root__'
    | '/'
    | '/_anonymous'
    | '/_authenticated'
    | '/_anonymous/login'
    | '/_anonymous/signup'
    | '/_authenticated/_organizationRequired'
    | '/_authenticated/_organizationRequired/home'
    | '/_authenticated/_organizationRequired/environments/create'
    | '/_authenticated/_organizationRequired/flags/create'
    | '/_authenticated/_organizationRequired/projects/create'
    | '/_authenticated/_organizationRequired/environments/'
    | '/_authenticated/_organizationRequired/flags/'
    | '/_authenticated/_organizationRequired/projects/'
    | '/_authenticated/_organizationRequired/project/$projectName/'
    | '/_authenticated/_organizationRequired/project/$projectName/environment/$environmentName'
    | '/_authenticated/_organizationRequired/project/$projectName/flag/$flagName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnonymousRoute: typeof AnonymousRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anonymous': {
      id: '/_anonymous'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AnonymousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anonymous/login': {
      id: '/_anonymous/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AnonymousLoginRouteImport
      parentRoute: typeof AnonymousRoute
    }
    '/_anonymous/signup': {
      id: '/_anonymous/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AnonymousSignupRouteImport
      parentRoute: typeof AnonymousRoute
    }
    '/_authenticated/_organizationRequired': {
      id: '/_authenticated/_organizationRequired'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_organizationRequired/home': {
      id: '/_authenticated/_organizationRequired/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredHomeRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/environments/': {
      id: '/_authenticated/_organizationRequired/environments/'
      path: '/environments'
      fullPath: '/environments/'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredEnvironmentsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/environments/create': {
      id: '/_authenticated/_organizationRequired/environments/create'
      path: '/environments/create'
      fullPath: '/environments/create'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredEnvironmentsCreateRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/flags/': {
      id: '/_authenticated/_organizationRequired/flags/'
      path: '/flags'
      fullPath: '/flags/'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredFlagsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/flags/create': {
      id: '/_authenticated/_organizationRequired/flags/create'
      path: '/flags/create'
      fullPath: '/flags/create'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredFlagsCreateRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/projects/': {
      id: '/_authenticated/_organizationRequired/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/projects/create': {
      id: '/_authenticated/_organizationRequired/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/project/$projectName/': {
      id: '/_authenticated/_organizationRequired/project/$projectName/'
      path: '/project/$projectName'
      fullPath: '/project/$projectName/'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredProjectProjectNameIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/project/$projectName/environment/$environmentName': {
      id: '/_authenticated/_organizationRequired/project/$projectName/environment/$environmentName'
      path: '/project/$projectName/environment/$environmentName'
      fullPath: '/project/$projectName/environment/$environmentName'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/project/$projectName/flag/$flagName': {
      id: '/_authenticated/_organizationRequired/project/$projectName/flag/$flagName'
      path: '/project/$projectName/flag/$flagName'
      fullPath: '/project/$projectName/flag/$flagName'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
  }
}

interface AnonymousRouteChildren {
  AnonymousLoginRoute: typeof AnonymousLoginRoute
  AnonymousSignupRoute: typeof AnonymousSignupRoute
}

const AnonymousRouteChildren: AnonymousRouteChildren = {
  AnonymousLoginRoute: AnonymousLoginRoute,
  AnonymousSignupRoute: AnonymousSignupRoute,
}

const AnonymousRouteWithChildren = AnonymousRoute._addFileChildren(
  AnonymousRouteChildren,
)

interface AuthenticatedOrganizationRequiredRouteChildren {
  AuthenticatedOrganizationRequiredHomeRoute: typeof AuthenticatedOrganizationRequiredHomeRoute
  AuthenticatedOrganizationRequiredEnvironmentsCreateRoute: typeof AuthenticatedOrganizationRequiredEnvironmentsCreateRoute
  AuthenticatedOrganizationRequiredFlagsCreateRoute: typeof AuthenticatedOrganizationRequiredFlagsCreateRoute
  AuthenticatedOrganizationRequiredProjectsCreateRoute: typeof AuthenticatedOrganizationRequiredProjectsCreateRoute
  AuthenticatedOrganizationRequiredEnvironmentsIndexRoute: typeof AuthenticatedOrganizationRequiredEnvironmentsIndexRoute
  AuthenticatedOrganizationRequiredFlagsIndexRoute: typeof AuthenticatedOrganizationRequiredFlagsIndexRoute
  AuthenticatedOrganizationRequiredProjectsIndexRoute: typeof AuthenticatedOrganizationRequiredProjectsIndexRoute
  AuthenticatedOrganizationRequiredProjectProjectNameIndexRoute: typeof AuthenticatedOrganizationRequiredProjectProjectNameIndexRoute
  AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRoute: typeof AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRoute
  AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRoute: typeof AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRoute
}

const AuthenticatedOrganizationRequiredRouteChildren: AuthenticatedOrganizationRequiredRouteChildren =
  {
    AuthenticatedOrganizationRequiredHomeRoute:
      AuthenticatedOrganizationRequiredHomeRoute,
    AuthenticatedOrganizationRequiredEnvironmentsCreateRoute:
      AuthenticatedOrganizationRequiredEnvironmentsCreateRoute,
    AuthenticatedOrganizationRequiredFlagsCreateRoute:
      AuthenticatedOrganizationRequiredFlagsCreateRoute,
    AuthenticatedOrganizationRequiredProjectsCreateRoute:
      AuthenticatedOrganizationRequiredProjectsCreateRoute,
    AuthenticatedOrganizationRequiredEnvironmentsIndexRoute:
      AuthenticatedOrganizationRequiredEnvironmentsIndexRoute,
    AuthenticatedOrganizationRequiredFlagsIndexRoute:
      AuthenticatedOrganizationRequiredFlagsIndexRoute,
    AuthenticatedOrganizationRequiredProjectsIndexRoute:
      AuthenticatedOrganizationRequiredProjectsIndexRoute,
    AuthenticatedOrganizationRequiredProjectProjectNameIndexRoute:
      AuthenticatedOrganizationRequiredProjectProjectNameIndexRoute,
    AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRoute:
      AuthenticatedOrganizationRequiredProjectProjectNameEnvironmentEnvironmentNameRoute,
    AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRoute:
      AuthenticatedOrganizationRequiredProjectProjectNameFlagFlagNameRoute,
  }

const AuthenticatedOrganizationRequiredRouteWithChildren =
  AuthenticatedOrganizationRequiredRoute._addFileChildren(
    AuthenticatedOrganizationRequiredRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOrganizationRequiredRoute: typeof AuthenticatedOrganizationRequiredRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrganizationRequiredRoute:
    AuthenticatedOrganizationRequiredRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnonymousRoute: AnonymousRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
