/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnonymousRouteImport } from './routes/_anonymous'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AnonymousLoginRouteImport } from './routes/_anonymous/login'
import { Route as AnonymousSignupRouteImport } from './routes/_anonymous/signup'
import { Route as AuthenticatedOrganizationRequiredRouteImport } from './routes/_authenticated/_organizationRequired'
import { Route as AuthenticatedOrganizationRequiredHomeRouteImport } from './routes/_authenticated/_organizationRequired/home'
import { Route as AuthenticatedOrganizationRequiredProjectsIndexRouteImport } from './routes/_authenticated/_organizationRequired/projects/index'
import { Route as AuthenticatedOrganizationRequiredProjectsIdRouteImport } from './routes/_authenticated/_organizationRequired/projects/$id'
import { Route as AuthenticatedOrganizationRequiredProjectsCreateRouteImport } from './routes/_authenticated/_organizationRequired/projects/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousRoute = AnonymousRouteImport.update({
  id: '/_anonymous',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousLoginRoute = AnonymousLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AnonymousRoute,
} as any)
const AnonymousSignupRoute = AnonymousSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AnonymousRoute,
} as any)
const AuthenticatedOrganizationRequiredRoute =
  AuthenticatedOrganizationRequiredRouteImport.update({
    id: '/_organizationRequired',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationRequiredHomeRoute =
  AuthenticatedOrganizationRequiredHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredProjectsIndexRoute =
  AuthenticatedOrganizationRequiredProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredProjectsIdRoute =
  AuthenticatedOrganizationRequiredProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)
const AuthenticatedOrganizationRequiredProjectsCreateRoute =
  AuthenticatedOrganizationRequiredProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedOrganizationRequiredRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AnonymousLoginRoute
  '/signup': typeof AnonymousSignupRoute
  '/home': typeof AuthenticatedOrganizationRequiredHomeRoute
  '/projects/$id': typeof AuthenticatedOrganizationRequiredProjectsIdRoute
  '/projects/create': typeof AuthenticatedOrganizationRequiredProjectsCreateRoute
  '/projects/': typeof AuthenticatedOrganizationRequiredProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AnonymousLoginRoute
  '/signup': typeof AnonymousSignupRoute
  '/home': typeof AuthenticatedOrganizationRequiredHomeRoute
  '/projects/$id': typeof AuthenticatedOrganizationRequiredProjectsIdRoute
  '/projects/create': typeof AuthenticatedOrganizationRequiredProjectsCreateRoute
  '/projects': typeof AuthenticatedOrganizationRequiredProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_anonymous': typeof AnonymousRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_anonymous/login': typeof AnonymousLoginRoute
  '/_anonymous/signup': typeof AnonymousSignupRoute
  '/_authenticated/_organizationRequired': typeof AuthenticatedOrganizationRequiredRouteWithChildren
  '/_authenticated/_organizationRequired/home': typeof AuthenticatedOrganizationRequiredHomeRoute
  '/_authenticated/_organizationRequired/projects/$id': typeof AuthenticatedOrganizationRequiredProjectsIdRoute
  '/_authenticated/_organizationRequired/projects/create': typeof AuthenticatedOrganizationRequiredProjectsCreateRoute
  '/_authenticated/_organizationRequired/projects/': typeof AuthenticatedOrganizationRequiredProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/projects/$id'
    | '/projects/create'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/projects/$id'
    | '/projects/create'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_anonymous'
    | '/_authenticated'
    | '/_anonymous/login'
    | '/_anonymous/signup'
    | '/_authenticated/_organizationRequired'
    | '/_authenticated/_organizationRequired/home'
    | '/_authenticated/_organizationRequired/projects/$id'
    | '/_authenticated/_organizationRequired/projects/create'
    | '/_authenticated/_organizationRequired/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnonymousRoute: typeof AnonymousRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anonymous': {
      id: '/_anonymous'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AnonymousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anonymous/login': {
      id: '/_anonymous/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AnonymousLoginRouteImport
      parentRoute: typeof AnonymousRoute
    }
    '/_anonymous/signup': {
      id: '/_anonymous/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AnonymousSignupRouteImport
      parentRoute: typeof AnonymousRoute
    }
    '/_authenticated/_organizationRequired': {
      id: '/_authenticated/_organizationRequired'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_organizationRequired/home': {
      id: '/_authenticated/_organizationRequired/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredHomeRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/projects/': {
      id: '/_authenticated/_organizationRequired/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/projects/$id': {
      id: '/_authenticated/_organizationRequired/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredProjectsIdRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
    '/_authenticated/_organizationRequired/projects/create': {
      id: '/_authenticated/_organizationRequired/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedOrganizationRequiredProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedOrganizationRequiredRoute
    }
  }
}

interface AnonymousRouteChildren {
  AnonymousLoginRoute: typeof AnonymousLoginRoute
  AnonymousSignupRoute: typeof AnonymousSignupRoute
}

const AnonymousRouteChildren: AnonymousRouteChildren = {
  AnonymousLoginRoute: AnonymousLoginRoute,
  AnonymousSignupRoute: AnonymousSignupRoute,
}

const AnonymousRouteWithChildren = AnonymousRoute._addFileChildren(
  AnonymousRouteChildren,
)

interface AuthenticatedOrganizationRequiredRouteChildren {
  AuthenticatedOrganizationRequiredHomeRoute: typeof AuthenticatedOrganizationRequiredHomeRoute
  AuthenticatedOrganizationRequiredProjectsIdRoute: typeof AuthenticatedOrganizationRequiredProjectsIdRoute
  AuthenticatedOrganizationRequiredProjectsCreateRoute: typeof AuthenticatedOrganizationRequiredProjectsCreateRoute
  AuthenticatedOrganizationRequiredProjectsIndexRoute: typeof AuthenticatedOrganizationRequiredProjectsIndexRoute
}

const AuthenticatedOrganizationRequiredRouteChildren: AuthenticatedOrganizationRequiredRouteChildren =
  {
    AuthenticatedOrganizationRequiredHomeRoute:
      AuthenticatedOrganizationRequiredHomeRoute,
    AuthenticatedOrganizationRequiredProjectsIdRoute:
      AuthenticatedOrganizationRequiredProjectsIdRoute,
    AuthenticatedOrganizationRequiredProjectsCreateRoute:
      AuthenticatedOrganizationRequiredProjectsCreateRoute,
    AuthenticatedOrganizationRequiredProjectsIndexRoute:
      AuthenticatedOrganizationRequiredProjectsIndexRoute,
  }

const AuthenticatedOrganizationRequiredRouteWithChildren =
  AuthenticatedOrganizationRequiredRoute._addFileChildren(
    AuthenticatedOrganizationRequiredRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOrganizationRequiredRoute: typeof AuthenticatedOrganizationRequiredRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrganizationRequiredRoute:
    AuthenticatedOrganizationRequiredRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnonymousRoute: AnonymousRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
