#############
### Tasks ###
#############

[tasks.install]
extends = "js:install"

[tasks.check]
extends = "js:check"

[tasks."check:ci"]
extends = "js:check:ci"

[tasks.build]
depends = ["//js/packages/sdk:build"]
extends = "js:build"

[tasks.dev]
description = "Start the project in development mode"
run = ["pnpm dev"]
