import {
  ArrowDownIcon,
  ArrowSquareOutIcon,
  ArrowsDownUpIcon,
  ArrowUpIcon,
  CalendarBlankIcon,
  CaretDoubleLeftIcon,
  CaretDoubleRightIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ChecksIcon,
  ClockIcon,
  ColumnsIcon,
  CopyIcon,
  DotsThreeIcon,
  EyeSlashIcon,
  FunnelIcon,
  InfoIcon,
  ListIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  StopIcon,
  WarningIcon,
  WrenchIcon,
  XCircleIcon,
  XIcon,
} from "@phosphor-icons/react";

export const phosphorIcons = {
  close: <XIcon />,
  chevronDown: <CaretDownIcon />,
  chevronLeft: <CaretLeftIcon />,
  chevronRight: <CaretRightIcon />,
  chevronsLeft: <CaretDoubleLeftIcon />,
  chevronsRight: <CaretDoubleRightIcon />,
  check: <CheckIcon />,
  success: <CheckCircleIcon />,
  error: <XCircleIcon />,
  warning: <WarningIcon />,
  info: <InfoIcon />,
  calendar: <CalendarBlankIcon />,
  clock: <ClockIcon />,
  externalLink: <ArrowSquareOutIcon />,
  menu: <ListIcon />,
  moreHorizontal: <DotsThreeIcon />,
  search: <MagnifyingGlassIcon />,
  arrowUp: <ArrowUpIcon />,
  arrowDown: <ArrowDownIcon />,
  arrowsUpDown: <ArrowsDownUpIcon />,
  funnel: <FunnelIcon />,
  eyeSlash: <EyeSlashIcon />,
  viewColumns: <ColumnsIcon />,
  copy: <CopyIcon />,
  checkDouble: <ChecksIcon />,
  wrench: <WrenchIcon />,
  stop: <StopIcon />,
  microphone: <MicrophoneIcon />,
};
