defmodule RailswitchBackend.Repo.Migrations.AddLastUsedToEnvironmentApiKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:environment_api_keys) do
      add :last_used, :utc_datetime
    end
  end

  def down do
    alter table(:environment_api_keys) do
      remove :last_used
    end
  end
end
