defmodule RailswitchBackend.Repo.Migrations.MakeUniqueNamesCaseInsensitive do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      modify :name, :citext
    end

    alter table(:flags) do
      modify :name, :citext
    end

    alter table(:environments) do
      modify :name, :citext
    end
  end

  def down do
    alter table(:environments) do
      modify :name, :text
    end

    alter table(:flags) do
      modify :name, :text
    end

    alter table(:projects) do
      modify :name, :text
    end
  end
end
