defmodule RailswitchBackend.Repo.Migrations.CreateFlagResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:flags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "flags_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "flags_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:flags, [:organization_id, :project_id, :name],
             name: "flags_unique_name_index"
           )
  end

  def down do
    drop constraint(:flags, "flags_organization_id_fkey")

    drop constraint(:flags, "flags_project_id_fkey")

    drop_if_exists unique_index(:flags, [:organization_id, :project_id, :name],
                     name: "flags_unique_name_index"
                   )

    drop table(:flags)
  end
end
