defmodule RailswitchBackend.Repo.Migrations.CleanUpCascadingDeletes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:project_api_keys, "project_api_keys_organization_id_fkey")

    alter table(:project_api_keys) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "project_api_keys_organization_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:project_api_keys, "project_api_keys_organization_id_fkey")

    alter table(:project_api_keys) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "project_api_keys_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
