defmodule RailswitchBackend.Repo.Migrations.MoveApiKeysToEnvironments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:project_api_keys), to: table(:environment_api_keys)

    alter table(:environment_api_keys) do
      remove :project_id
    end

    drop constraint(:environment_api_keys, "project_api_keys_organization_id_fkey")

    alter table(:environment_api_keys) do
      add :environment_id,
          references(:environments,
            column: :id,
            name: "environment_api_keys_environment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "environment_api_keys_organization_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute(
      "ALTER INDEX project_api_keys_unique_api_key_index RENAME TO environment_api_keys_unique_api_key_index"
    )
  end

  def down do
    execute(
      "ALTER INDEX environment_api_keys_unique_api_key_index RENAME TO project_api_keys_unique_api_key_index"
    )

    drop constraint(:environment_api_keys, "environment_api_keys_environment_id_fkey")

    drop constraint(:environment_api_keys, "environment_api_keys_organization_id_fkey")

    alter table(:environment_api_keys) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "project_api_keys_organization_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      remove :environment_id
    end

    alter table(:environment_api_keys) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "project_api_keys_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    rename table(:environment_api_keys), to: table(:project_api_keys)
  end
end
