defmodule RailswitchBackend.Repo.Migrations.AddApiAuthenticationForProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:project_api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_hash, :binary, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "project_api_keys_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_api_keys_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:project_api_keys, [:api_key_hash],
             name: "project_api_keys_unique_api_key_index"
           )
  end

  def down do
    drop constraint(:project_api_keys, "project_api_keys_organization_id_fkey")

    drop constraint(:project_api_keys, "project_api_keys_project_id_fkey")

    drop_if_exists unique_index(:project_api_keys, [:api_key_hash],
                     name: "project_api_keys_unique_api_key_index"
                   )

    drop table(:project_api_keys)
  end
end
