defmodule RailswitchBackend.Repo.Migrations.CreateFlagEnvironmentResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:flag_environments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :rules, :map, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "flag_environments_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :flag_id,
          references(:flags,
            column: :id,
            name: "flag_environments_flag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :environment_id,
          references(:environments,
            column: :id,
            name: "flag_environments_environment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:flag_environments, [:organization_id, :environment_id, :flag_id],
             name: "flag_environments_flag_environment_key_index"
           )
  end

  def down do
    drop constraint(:flag_environments, "flag_environments_organization_id_fkey")

    drop constraint(:flag_environments, "flag_environments_flag_id_fkey")

    drop constraint(:flag_environments, "flag_environments_environment_id_fkey")

    drop_if_exists unique_index(:flag_environments, [:organization_id, :environment_id, :flag_id],
                     name: "flag_environments_flag_environment_key_index"
                   )

    drop table(:flag_environments)
  end
end
