#############
### Tasks ###
#############

[tasks.install]
extends = "js:install"

[tasks.check]
extends = "js:check"

[tasks."check:ci"]
extends = "js:check:ci"

[tasks.typecheck]
extends = "js:typecheck"

[tasks.test]
extends = "js:test"

[tasks."test:watch"]
extends = "js:test:watch"
